### ISSUE TITLE
sql doesn't have "essentialmode.licenses"

### ISSUE THREAD

**Issue by 0x01422** [HumanTree92/esx_advancedweaponshop#3]
The sql wants to import something to essentialmode.licenses but there is no because esx_licenseshop has no sql to create table licenses.
Is there any "CREATE TABLE 'licenses'" that i missed?

**Comment by HumanTree92** [comment]
Must not have read the readme. You need esx_licenseshop which that will need esx_dmvschool

**Comment by 0x01422** [comment]
Oh im very sorry! Thanks for the help!
