### ISSUE TITLE
Ammo Box and Ammo Clip Nil

### ISSUE THREAD

**Issue by awidyaandika** [HumanTree92/esx_advancedweaponshop#5]
Hello, I want to ask something. I added Ammo Box and Ammo Clip to Weapon Shop in the Handgun category. But the display from that ammo (box and clip) is Nil-

![Screenshot_11](https://user-images.githubusercontent.com/63634198/89213782-31109f00-d5f8-11ea-8f27-7f885c1b8a98.png)

How to rename that (Nil-) to be Ammo Box and Clip?

**Comment by HumanTree92** [comment]
You should setup a shop script like esx_shops to have it not say nil. By default this script doesn't support Ammo Clip or Weapon Box. No way to fix this issue.
