### ISSUE TITLE
Easy way to integrate box ammos in shop ? (esx_extraitems)

### ISSUE THREAD

**Issue by mckilleron** [HumanTree92/esx_advancedweaponshop#6]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?:  No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No 
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.2 
Are you using Essentialmode?: Yes
Are you using ExtendedMode?: Yes
Are you using OneSync?: Yes
Linux or Windows?: Windows

Hi, i would like to know if there easy way to add ammo boxes from esx extraitems to ammunation shops ?

Regards

**Comment by HumanTree92** [comment]
no
