### ISSUE TITLE
Cannot get my vehicle out when i put it away

### ISSUE THREAD

**Issue by madalex24** [HumanTree92/esx_advancedweaponshop#8]
I bought a vehicle and then when i tried to get it out again, it says no vehicle available

**Questions**
Have you made changes to anything besides the `config.lua`?: 
Have you looked through the Closed Topics?: Yes, there was a solution but it was deleted.
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: 
Are you using ESX Legacy?: Yes
Are you using OneSync?: 
Linux or Windows?: Windows

![owned vehicles data](https://user-images.githubusercontent.com/91700454/135769032-d51a683e-da02-4092-aa63-1249978efaf7.png)
![owned vehicles structure](https://user-images.githubusercontent.com/91700454/135769033-3f052f92-63a5-4640-8ad0-0cac9196bdf4.png)

**Comment by HumanTree92** [comment]
Wrong script. I think your looking for esx_advancedvehicleshop and not esx_advancedweaponshop. But maybe read the Readme for how to install esx_advancedvehicleshop b/c your image doesn't look like its supposed to be like that.
